---
# HypixelBow Configuration File

# will send to launched player and hit the projectile
# not to send, set to false.
#
# Replacement
#
# {hp{      : player's health
# {damage}  : amount of damage
# {rawname} : player's name (no tag)
# {name}    : player's display name

hit-message: "§dHP §e-> §b{name} §7(§aHP: §e{hp}§7)"
...
